// ReactBits Component Integration
// This file maps ReactBits components from the cloned repository

export const REACTBITS_PATH = '../designbits/react-bits/src';

export const COMPONENT_PATHS = {
  // Text Animations
  'split-text': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/SplitText`,
  'blur-text': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/BlurText`,
  'circular-text': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/CircularText`,
  'shiny-text': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/ShinyText`,
  'text-pressure': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/TextPressure`,
  'curved-loop': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/CurvedLoop`,
  'fuzzy-text': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/FuzzyText`,
  'gradient-text': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/GradientText`,
  'text-trail': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/TextTrail`,
  'falling-text': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/FallingText`,
  'text-cursor': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/TextCursor`,
  'decrypted-text': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/DecryptedText`,
  'true-focus': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/TrueFocus`,
  'scroll-float': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/ScrollFloat`,
  'scroll-reveal': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/ScrollReveal`,
  'ascii-text': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/ASCIIText`,
  'scramble-text': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/ScrambleText`,
  'rotating-text': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/RotatingText`,
  'glitch-text': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/GlitchText`,
  'scroll-velocity': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/ScrollVelocity`,
  'variable-proximity': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/VariableProximity`,
  'count-up': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/CountUp`,
  'rolling-text': `${REACTBITS_PATH}/ts-tailwind/TextAnimations/RollingText`,

  // Animations
  'animated-content': `${REACTBITS_PATH}/ts-tailwind/Animations/AnimatedContent`,
  'fade-content': `${REACTBITS_PATH}/ts-tailwind/Animations/FadeContent`,
  'pixel-transition': `${REACTBITS_PATH}/ts-tailwind/Animations/PixelTransition`,
  'glare-hover': `${REACTBITS_PATH}/ts-tailwind/Animations/GlareHover`,
  'target-cursor': `${REACTBITS_PATH}/ts-tailwind/Animations/TargetCursor`,
  'magnet-lines': `${REACTBITS_PATH}/ts-tailwind/Animations/MagnetLines`,
  'click-spark': `${REACTBITS_PATH}/ts-tailwind/Animations/ClickSpark`,
  'magnet': `${REACTBITS_PATH}/ts-tailwind/Animations/Magnet`,
  'pixel-trail': `${REACTBITS_PATH}/ts-tailwind/Animations/PixelTrail`,
  'cubes': `${REACTBITS_PATH}/ts-tailwind/Animations/Cubes`,
  'metallic-paint': `${REACTBITS_PATH}/ts-tailwind/Animations/MetallicPaint`,
  'noise': `${REACTBITS_PATH}/ts-tailwind/Animations/Noise`,
  'shape-blur': `${REACTBITS_PATH}/ts-tailwind/Animations/ShapeBlur`,
  'crosshair': `${REACTBITS_PATH}/ts-tailwind/Animations/Crosshair`,
  'image-trail': `${REACTBITS_PATH}/ts-tailwind/Animations/ImageTrail`,
  'ribbons': `${REACTBITS_PATH}/ts-tailwind/Animations/Ribbons`,
  'splash-cursor': `${REACTBITS_PATH}/ts-tailwind/Animations/SplashCursor`,
  'meta-balls': `${REACTBITS_PATH}/ts-tailwind/Animations/MetaBalls`,
  'blob-cursor': `${REACTBITS_PATH}/ts-tailwind/Animations/BlobCursor`,
  'star-border': `${REACTBITS_PATH}/ts-tailwind/Animations/StarBorder`,
  'bounce': `${REACTBITS_PATH}/ts-tailwind/Animations/Bounce`,

  // Components
  'animated-list': `${REACTBITS_PATH}/ts-tailwind/Components/AnimatedList`,
  'scroll-stack': `${REACTBITS_PATH}/ts-tailwind/Components/ScrollStack`,
  'magic-bento': `${REACTBITS_PATH}/ts-tailwind/Components/MagicBento`,
  'circular-gallery': `${REACTBITS_PATH}/ts-tailwind/Components/CircularGallery`,
  'stack': `${REACTBITS_PATH}/ts-tailwind/Components/Stack`,
  'fluid-glass': `${REACTBITS_PATH}/ts-tailwind/Components/FluidGlass`,
  'tilted-card': `${REACTBITS_PATH}/ts-tailwind/Components/TiltedCard`,
  'masonry': `${REACTBITS_PATH}/ts-tailwind/Components/Masonry`,
  'glass-surface': `${REACTBITS_PATH}/ts-tailwind/Components/GlassSurface`,
  'chroma-grid': `${REACTBITS_PATH}/ts-tailwind/Components/ChromaGrid`,
  'folder': `${REACTBITS_PATH}/ts-tailwind/Components/Folder`,
  'model-viewer': `${REACTBITS_PATH}/ts-tailwind/Components/ModelViewer`,
  'lanyard': `${REACTBITS_PATH}/ts-tailwind/Components/Lanyard`,
  'profile-card': `${REACTBITS_PATH}/ts-tailwind/Components/ProfileCard`,
  'dock': `${REACTBITS_PATH}/ts-tailwind/Components/Dock`,
  'gooey-nav': `${REACTBITS_PATH}/ts-tailwind/Components/GooeyNav`,
  'pixel-card': `${REACTBITS_PATH}/ts-tailwind/Components/PixelCard`,
  'carousel': `${REACTBITS_PATH}/ts-tailwind/Components/Carousel`,
  'spotlight-card': `${REACTBITS_PATH}/ts-tailwind/Components/SpotlightCard`,
  'flying-posters': `${REACTBITS_PATH}/ts-tailwind/Components/FlyingPosters`,
  'card-swap': `${REACTBITS_PATH}/ts-tailwind/Components/CardSwap`,
  'infinite-scroll': `${REACTBITS_PATH}/ts-tailwind/Components/InfiniteScroll`,
  'glass-icons': `${REACTBITS_PATH}/ts-tailwind/Components/GlassIcons`,
  'decay-card': `${REACTBITS_PATH}/ts-tailwind/Components/DecayCard`,
  'flowing-menu': `${REACTBITS_PATH}/ts-tailwind/Components/FlowingMenu`,
  'elastic-slider': `${REACTBITS_PATH}/ts-tailwind/Components/ElasticSlider`,
  'counter': `${REACTBITS_PATH}/ts-tailwind/Components/Counter`,
  'infinite-menu': `${REACTBITS_PATH}/ts-tailwind/Components/InfiniteMenu`,
  'rolling-gallery': `${REACTBITS_PATH}/ts-tailwind/Components/RollingGallery`,
  'stepper': `${REACTBITS_PATH}/ts-tailwind/Components/Stepper`,
  'bounce-cards': `${REACTBITS_PATH}/ts-tailwind/Components/BounceCards`,

  // Backgrounds
  'dark-veil': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/DarkVeil`,
  'silk': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Silk`,
  'aurora': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Aurora`,
  'particles': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Particles`,
  'beams': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Beams`,
  'lightning': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Lightning`,
  'dither': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Dither`,
  'ripple-grid': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/RippleGrid`,
  'dot-grid': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/DotGrid`,
  'threads': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Threads`,
  'hyperspeed': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Hyperspeed`,
  'iridescence': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Iridescence`,
  'waves': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Waves`,
  'grid-distortion': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/GridDistortion`,
  'ballpit': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Ballpit`,
  'orb': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Orb`,
  'letter-glitch': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/LetterGlitch`,
  'grid-motion': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/GridMotion`,
  'squares': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Squares`,
  'liquid-chrome': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/LiquidChrome`,
  'balatro': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Balatro`,
  'grid': `${REACTBITS_PATH}/ts-tailwind/Backgrounds/Grid`,
};