import { ComponentDefinition } from '@/types/builder';

interface ComponentSize {
  width: string;
  height: string;
}

export const defaultSizes: Record<string, ComponentSize> = {
  // Text Animations
  'split-text': { width: '400px', height: 'auto' },
  'blur-text': { width: '400px', height: 'auto' },
  'circular-text': { width: '300px', height: '300px' },
  'shiny-text': { width: '400px', height: 'auto' },
  'text-pressure': { width: '400px', height: 'auto' },
  'curved-loop': { width: '500px', height: '200px' },
  'fuzzy-text': { width: '400px', height: 'auto' },
  'gradient-text': { width: '400px', height: 'auto' },
  'text-trail': { width: '400px', height: 'auto' },
  'falling-text': { width: '400px', height: '200px' },
  'text-cursor': { width: '400px', height: 'auto' },
  'decrypted-text': { width: '400px', height: 'auto' },
  'true-focus': { width: '400px', height: 'auto' },
  'scroll-float': { width: '100%', height: '300px' },
  'scroll-reveal': { width: '100%', height: '200px' },
  'ascii-text': { width: '400px', height: 'auto' },
  'scramble-text': { width: '400px', height: 'auto' },
  'rotating-text': { width: '400px', height: 'auto' },
  'glitch-text': { width: '400px', height: 'auto' },
  'scroll-velocity': { width: '100%', height: '100px' },
  'variable-proximity': { width: '600px', height: '200px' },
  'count-up': { width: '200px', height: 'auto' },
  'rolling-text': { width: '400px', height: 'auto' },

  // Animations
  'animated-content': { width: '400px', height: '300px' },
  'fade-content': { width: '400px', height: '300px' },
  'pixel-transition': { width: '400px', height: '300px' },
  'glare-hover': { width: '300px', height: '200px' },
  'target-cursor': { width: '100%', height: '400px' },
  'magnet-lines': { width: '600px', height: '400px' },
  'click-spark': { width: '300px', height: '200px' },
  'magnet': { width: '200px', height: '100px' },
  'pixel-trail': { width: '100%', height: '400px' },
  'cubes': { width: '600px', height: '400px' },
  'metallic-paint': { width: '600px', height: '400px' },
  'noise': { width: '400px', height: '300px' },
  'shape-blur': { width: '400px', height: '400px' },
  'crosshair': { width: '100%', height: '400px' },
  'image-trail': { width: '100%', height: '400px' },
  'ribbons': { width: '100%', height: '400px' },
  'splash-cursor': { width: '100%', height: '400px' },
  'meta-balls': { width: '600px', height: '400px' },
  'blob-cursor': { width: '100%', height: '400px' },
  'star-border': { width: '300px', height: '200px' },
  'bounce': { width: '200px', height: '150px' },

  // Components
  'animated-list': { width: '400px', height: '400px' },
  'scroll-stack': { width: '100%', height: '600px' },
  'magic-bento': { width: '600px', height: '400px' },
  'circular-gallery': { width: '600px', height: '600px' },
  'stack': { width: '400px', height: '500px' },
  'fluid-glass': { width: '400px', height: '300px' },
  'tilted-card': { width: '350px', height: '200px' },
  'masonry': { width: '100%', height: '600px' },
  'glass-surface': { width: '400px', height: '300px' },
  'chroma-grid': { width: '600px', height: '600px' },
  'folder': { width: '300px', height: '400px' },
  'model-viewer': { width: '600px', height: '400px' },
  'lanyard': { width: '350px', height: '120px' },
  'profile-card': { width: '350px', height: '450px' },
  'dock': { width: '600px', height: '80px' },
  'gooey-nav': { width: '400px', height: '60px' },
  'pixel-card': { width: '350px', height: '200px' },
  'carousel': { width: '100%', height: '400px' },
  'spotlight-card': { width: '350px', height: '200px' },
  'flying-posters': { width: '100%', height: '600px' },
  'card-swap': { width: '400px', height: '500px' },
  'infinite-scroll': { width: '100%', height: '400px' },
  'glass-icons': { width: '400px', height: '100px' },
  'decay-card': { width: '350px', height: '200px' },
  'flowing-menu': { width: '300px', height: '400px' },
  'elastic-slider': { width: '100%', height: '400px' },
  'counter': { width: '200px', height: '100px' },
  'infinite-menu': { width: '100%', height: '60px' },
  'rolling-gallery': { width: '100%', height: '400px' },
  'stepper': { width: '600px', height: '100px' },
  'bounce-cards': { width: '600px', height: '400px' },

  // Backgrounds
  'dark-veil': { width: '100%', height: '400px' },
  'silk': { width: '100%', height: '400px' },
  'aurora': { width: '100%', height: '400px' },
  'particles': { width: '100%', height: '400px' },
  'beams': { width: '100%', height: '400px' },
  'lightning': { width: '100%', height: '400px' },
  'dither': { width: '100%', height: '400px' },
  'ripple-grid': { width: '100%', height: '400px' },
  'dot-grid': { width: '100%', height: '400px' },
  'threads': { width: '100%', height: '400px' },
  'hyperspeed': { width: '100%', height: '400px' },
  'iridescence': { width: '100%', height: '400px' },
  'waves': { width: '100%', height: '400px' },
  'grid-distortion': { width: '100%', height: '400px' },
  'ballpit': { width: '100%', height: '400px' },
  'orb': { width: '100%', height: '400px' },
  'letter-glitch': { width: '100%', height: '400px' },
  'grid-motion': { width: '100%', height: '400px' },
  'squares': { width: '100%', height: '400px' },
  'liquid-chrome': { width: '100%', height: '400px' },
  'balatro': { width: '100%', height: '400px' },
  'grid': { width: '100%', height: '400px' },
};

export const allComponentDefinitions: ComponentDefinition[] = [
  // ===== TEXT ANIMATIONS =====
  {
    type: 'split-text',
    name: 'Split Text',
    category: 'text',
    icon: 'SplitSquareHorizontal',
    defaultProps: {
      text: 'Split Text Effect',
      delay: 0.05,
      duration: 0.6,
      splitType: 'words',
    },
    configSchema: [
      { key: 'text', label: 'Text Content', type: 'string', defaultValue: 'Split Text Effect' },
      { key: 'delay', label: 'Stagger Delay', type: 'number', defaultValue: 0.05, min: 0, max: 0.5, step: 0.01 },
      { key: 'duration', label: 'Animation Duration', type: 'number', defaultValue: 0.6, min: 0.1, max: 2, step: 0.1 },
      {
        key: 'splitType',
        label: 'Split By',
        type: 'select',
        options: [
          { value: 'chars', label: 'Characters' },
          { value: 'words', label: 'Words' },
        ],
        defaultValue: 'words',
      },
    ],
  },
  {
    type: 'blur-text',
    name: 'Blur Text',
    category: 'text',
    icon: 'Type',
    defaultProps: {
      text: 'Blur Animation',
      delay: 200,
      animateBy: 'words',
      direction: 'top',
    },
    configSchema: [
      { key: 'text', label: 'Text Content', type: 'string', defaultValue: 'Blur Animation' },
      { key: 'delay', label: 'Delay (ms)', type: 'number', defaultValue: 200, min: 0, max: 1000, step: 50 },
      { 
        key: 'animateBy', 
        label: 'Animate By', 
        type: 'select',
        options: [
          { value: 'words', label: 'Words' },
          { value: 'letters', label: 'Letters' },
        ],
        defaultValue: 'words' 
      },
      { 
        key: 'direction', 
        label: 'Direction', 
        type: 'select',
        options: [
          { value: 'top', label: 'Top' },
          { value: 'bottom', label: 'Bottom' },
        ],
        defaultValue: 'top' 
      },
    ],
  },
  {
    type: 'circular-text',
    name: 'Circular Text',
    category: 'text',
    icon: 'CircleDot',
    defaultProps: {
      children: 'Circular Text Animation • ',
      radius: 100,
      fontSize: 16,
    },
    configSchema: [
      { key: 'children', label: 'Text Content', type: 'string', defaultValue: 'Circular Text Animation • ' },
      { key: 'radius', label: 'Radius', type: 'number', defaultValue: 100, min: 50, max: 200, step: 10 },
      { key: 'fontSize', label: 'Font Size', type: 'number', defaultValue: 16, min: 12, max: 48, step: 2 },
    ],
  },
  {
    type: 'shiny-text',
    name: 'Shiny Text',
    category: 'text',
    icon: 'Sparkles',
    defaultProps: {
      children: 'Shiny Text',
      shimmerWidth: 100,
    },
    configSchema: [
      { key: 'children', label: 'Text Content', type: 'string', defaultValue: 'Shiny Text' },
      { key: 'shimmerWidth', label: 'Shimmer Width', type: 'number', defaultValue: 100, min: 50, max: 200, step: 10 },
    ],
  },
  {
    type: 'gradient-text',
    name: 'Gradient Text',
    category: 'text',
    icon: 'Palette',
    defaultProps: {
      children: 'Gradient Text',
      colors: ['#ffaa40', '#9c40ff', '#ffaa40'],
      animationSpeed: 8,
      showBorder: false,
    },
    configSchema: [
      { key: 'children', label: 'Text Content', type: 'string', defaultValue: 'Gradient Text' },
      { key: 'animationSpeed', label: 'Animation Speed', type: 'number', defaultValue: 8, min: 1, max: 20, step: 1 },
      { key: 'showBorder', label: 'Show Border', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'glitch-text',
    name: 'Glitch Text',
    category: 'text',
    icon: 'Zap',
    defaultProps: {
      children: 'GLITCH',
      speed: 0.5,
      enableShadows: true,
      enableOnHover: false,
    },
    configSchema: [
      { key: 'children', label: 'Text Content', type: 'string', defaultValue: 'GLITCH' },
      { key: 'speed', label: 'Animation Speed', type: 'number', defaultValue: 0.5, min: 0.1, max: 2, step: 0.1 },
      { key: 'enableShadows', label: 'Enable Shadows', type: 'boolean', defaultValue: true },
      { key: 'enableOnHover', label: 'Enable on Hover', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'scramble-text',
    name: 'Scramble Text',
    category: 'text',
    icon: 'Shuffle',
    defaultProps: {
      text: 'Scramble Text',
      fontSize: '36px',
      color: '#ffffff',
      duration: 2,
    },
    configSchema: [
      { key: 'text', label: 'Text Content', type: 'string', defaultValue: 'Scramble Text' },
      { key: 'fontSize', label: 'Font Size', type: 'string', defaultValue: '36px' },
      { key: 'color', label: 'Text Color', type: 'color', defaultValue: '#ffffff' },
      { key: 'duration', label: 'Animation Duration', type: 'number', defaultValue: 2, min: 0.5, max: 5, step: 0.5 },
    ],
  },
  {
    type: 'rolling-text',
    name: 'Rolling Text',
    category: 'text',
    icon: 'Type',
    defaultProps: {
      texts: ['Welcome', 'Hello', 'Greetings'],
      rotationInterval: 3000,
      auto: true,
      loop: true,
    },
    configSchema: [
      { key: 'texts', label: 'Text Array (comma separated)', type: 'string', defaultValue: 'Welcome,Hello,Greetings' },
      { key: 'rotationInterval', label: 'Rotation Interval (ms)', type: 'number', defaultValue: 3000, min: 1000, max: 10000, step: 500 },
      { key: 'auto', label: 'Auto Rotate', type: 'boolean', defaultValue: true },
      { key: 'loop', label: 'Loop', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'count-up',
    name: 'Count Up',
    category: 'text',
    icon: 'Hash',
    defaultProps: {
      from: 0,
      to: 100,
      duration: 2000,
      direction: 'up',
      delay: 0,
    },
    configSchema: [
      { key: 'from', label: 'Start Value', type: 'number', defaultValue: 0 },
      { key: 'to', label: 'End Value', type: 'number', defaultValue: 100 },
      { key: 'duration', label: 'Duration (ms)', type: 'number', defaultValue: 2000, min: 500, max: 10000, step: 500 },
      { 
        key: 'direction', 
        label: 'Direction', 
        type: 'select',
        options: [
          { value: 'up', label: 'Up' },
          { value: 'down', label: 'Down' },
        ],
        defaultValue: 'up' 
      },
      { key: 'delay', label: 'Delay (ms)', type: 'number', defaultValue: 0, min: 0, max: 5000, step: 100 },
    ],
  },
  {
    type: 'falling-text',
    name: 'Falling Text',
    category: 'text',
    icon: 'ChevronDown',
    defaultProps: {
      text: 'Falling Text',
      duration: 1.5,
      stagger: 0.05,
    },
    configSchema: [
      { key: 'text', label: 'Text Content', type: 'string', defaultValue: 'Falling Text' },
      { key: 'duration', label: 'Animation Duration', type: 'number', defaultValue: 1.5, min: 0.5, max: 3, step: 0.1 },
      { key: 'stagger', label: 'Stagger Delay', type: 'number', defaultValue: 0.05, min: 0, max: 0.2, step: 0.01 },
    ],
  },
  {
    type: 'fuzzy-text',
    name: 'Fuzzy Text',
    category: 'text',
    icon: 'CloudFog',
    defaultProps: {
      text: 'Fuzzy Text',
      delay: 2,
      duration: 0.8,
    },
    configSchema: [
      { key: 'text', label: 'Text Content', type: 'string', defaultValue: 'Fuzzy Text' },
      { key: 'delay', label: 'Delay (s)', type: 'number', defaultValue: 2, min: 0, max: 5, step: 0.5 },
      { key: 'duration', label: 'Animation Duration', type: 'number', defaultValue: 0.8, min: 0.3, max: 2, step: 0.1 },
    ],
  },
  {
    type: 'rotating-text',
    name: 'Rotating Text',
    category: 'text',
    icon: 'RotateCw',
    defaultProps: {
      words: ['Hello', 'World', 'Welcome'],
      duration: 2,
      stagger: 0.1,
    },
    configSchema: [
      { key: 'words', label: 'Words (comma separated)', type: 'string', defaultValue: 'Hello,World,Welcome' },
      { key: 'duration', label: 'Animation Duration', type: 'number', defaultValue: 2, min: 0.5, max: 5, step: 0.5 },
      { key: 'stagger', label: 'Stagger Delay', type: 'number', defaultValue: 0.1, min: 0, max: 0.5, step: 0.05 },
    ],
  },
  {
    type: 'ascii-text',
    name: 'ASCII Text',
    category: 'text',
    icon: 'Code',
    defaultProps: {
      text: 'ASCII',
      fontSize: 48,
      animationSpeed: 0.05,
    },
    configSchema: [
      { key: 'text', label: 'Text Content', type: 'string', defaultValue: 'ASCII' },
      { key: 'fontSize', label: 'Font Size', type: 'number', defaultValue: 48, min: 24, max: 120, step: 12 },
      { key: 'animationSpeed', label: 'Animation Speed', type: 'number', defaultValue: 0.05, min: 0.01, max: 0.2, step: 0.01 },
    ],
  },
  {
    type: 'curved-loop',
    name: 'Curved Loop',
    category: 'text',
    icon: 'Circle',
    defaultProps: {
      text: 'Curved Loop Text • ',
      repeat: 3,
      radius: 100,
      duration: 20,
    },
    configSchema: [
      { key: 'text', label: 'Text Content', type: 'string', defaultValue: 'Curved Loop Text • ' },
      { key: 'repeat', label: 'Text Repeat', type: 'number', defaultValue: 3, min: 1, max: 10, step: 1 },
      { key: 'radius', label: 'Curve Radius', type: 'number', defaultValue: 100, min: 50, max: 300, step: 25 },
      { key: 'duration', label: 'Animation Duration', type: 'number', defaultValue: 20, min: 5, max: 60, step: 5 },
    ],
  },
  {
    type: 'decrypted-text',
    name: 'Decrypted Text',
    category: 'text',
    icon: 'Key',
    defaultProps: {
      text: 'DECRYPTED',
      speed: 50,
      maxIterations: 30,
    },
    configSchema: [
      { key: 'text', label: 'Text Content', type: 'string', defaultValue: 'DECRYPTED' },
      { key: 'speed', label: 'Decryption Speed', type: 'number', defaultValue: 50, min: 20, max: 200, step: 10 },
      { key: 'maxIterations', label: 'Max Iterations', type: 'number', defaultValue: 30, min: 10, max: 100, step: 10 },
    ],
  },
  {
    type: 'scroll-float',
    name: 'Scroll Float',
    category: 'text',
    icon: 'MoveUp',
    defaultProps: {
      text: 'Scroll to Float',
      floatDistance: 50,
      duration: 1,
    },
    configSchema: [
      { key: 'text', label: 'Text Content', type: 'string', defaultValue: 'Scroll to Float' },
      { key: 'floatDistance', label: 'Float Distance', type: 'number', defaultValue: 50, min: 10, max: 200, step: 10 },
      { key: 'duration', label: 'Animation Duration', type: 'number', defaultValue: 1, min: 0.3, max: 3, step: 0.1 },
    ],
  },
  {
    type: 'scroll-reveal',
    name: 'Scroll Reveal',
    category: 'text',
    icon: 'Eye',
    defaultProps: {
      text: 'Scroll to Reveal',
      direction: 'up',
      delay: 0,
    },
    configSchema: [
      { key: 'text', label: 'Text Content', type: 'string', defaultValue: 'Scroll to Reveal' },
      { key: 'direction', label: 'Reveal Direction', type: 'select', options: [
        { value: 'up', label: 'Up' },
        { value: 'down', label: 'Down' },
        { value: 'left', label: 'Left' },
        { value: 'right', label: 'Right' },
      ], defaultValue: 'up' },
      { key: 'delay', label: 'Delay (s)', type: 'number', defaultValue: 0, min: 0, max: 2, step: 0.1 },
    ],
  },
  {
    type: 'scroll-velocity',
    name: 'Scroll Velocity',
    category: 'text',
    icon: 'FastForward',
    defaultProps: {
      text: 'SCROLL VELOCITY TEXT • ',
      velocity: 1,
      direction: 'horizontal',
    },
    configSchema: [
      { key: 'text', label: 'Text Content', type: 'string', defaultValue: 'SCROLL VELOCITY TEXT • ' },
      { key: 'velocity', label: 'Velocity Multiplier', type: 'number', defaultValue: 1, min: 0.5, max: 5, step: 0.5 },
      { key: 'direction', label: 'Direction', type: 'select', options: [
        { value: 'horizontal', label: 'Horizontal' },
        { value: 'vertical', label: 'Vertical' },
      ], defaultValue: 'horizontal' },
    ],
  },
  {
    type: 'text-cursor',
    name: 'Text Cursor',
    category: 'text',
    icon: 'MousePointer',
    defaultProps: {
      text: 'Hover Me',
      cursorSize: 80,
      cursorColor: '#6366f1',
    },
    configSchema: [
      { key: 'text', label: 'Text Content', type: 'string', defaultValue: 'Hover Me' },
      { key: 'cursorSize', label: 'Cursor Size', type: 'number', defaultValue: 80, min: 40, max: 200, step: 20 },
      { key: 'cursorColor', label: 'Cursor Color', type: 'color', defaultValue: '#6366f1' },
    ],
  },
  {
    type: 'text-pressure',
    name: 'Text Pressure',
    category: 'text',
    icon: 'MousePointer2',
    defaultProps: {
      text: 'Press Me',
      maxScale: 1.5,
      springConfig: { tension: 170, friction: 26 },
    },
    configSchema: [
      { key: 'text', label: 'Text Content', type: 'string', defaultValue: 'Press Me' },
      { key: 'maxScale', label: 'Max Scale', type: 'number', defaultValue: 1.5, min: 1, max: 3, step: 0.1 },
    ],
  },
  {
    type: 'text-trail',
    name: 'Text Trail',
    category: 'text',
    icon: 'Sparkles',
    defaultProps: {
      text: 'Move Mouse',
      trailLength: 10,
      fadeSpeed: 0.95,
    },
    configSchema: [
      { key: 'text', label: 'Text Content', type: 'string', defaultValue: 'Move Mouse' },
      { key: 'trailLength', label: 'Trail Length', type: 'number', defaultValue: 10, min: 5, max: 30, step: 5 },
      { key: 'fadeSpeed', label: 'Fade Speed', type: 'number', defaultValue: 0.95, min: 0.8, max: 0.99, step: 0.01 },
    ],
  },
  {
    type: 'true-focus',
    name: 'True Focus',
    category: 'text',
    icon: 'Focus',
    defaultProps: {
      sentence: 'True Focus',
      manualMode: false,
      blurAmount: 5,
      borderColor: 'green',
      glowColor: 'rgba(0, 255, 0, 0.6)',
      animationDuration: 0.5,
      pauseBetweenAnimations: 1,
    },
    configSchema: [
      { key: 'sentence', label: 'Text Content', type: 'string', defaultValue: 'True Focus' },
      { key: 'manualMode', label: 'Manual Mode', type: 'boolean', defaultValue: false },
      { key: 'blurAmount', label: 'Blur Amount', type: 'number', defaultValue: 5, min: 0, max: 20, step: 1 },
      { key: 'borderColor', label: 'Border Color', type: 'color', defaultValue: 'green' },
      { key: 'animationDuration', label: 'Animation Duration', type: 'number', defaultValue: 0.5, min: 0.1, max: 2, step: 0.1 },
      { key: 'pauseBetweenAnimations', label: 'Pause Duration', type: 'number', defaultValue: 1, min: 0.5, max: 5, step: 0.5 },
    ],
  },
  {
    type: 'variable-proximity',
    name: 'Variable Proximity',
    category: 'text',
    icon: 'Target',
    defaultProps: {
      label: 'Variable Font',
      fromFontVariationSettings: "'wght' 400, 'opsz' 9",
      toFontVariationSettings: "'wght' 800, 'opsz' 40",
      radius: 50,
      falloff: 'linear',
    },
    configSchema: [
      { key: 'label', label: 'Text Content', type: 'string', defaultValue: 'Variable Font' },
      { key: 'radius', label: 'Effect Radius', type: 'number', defaultValue: 50, min: 20, max: 200, step: 10 },
      { key: 'falloff', label: 'Falloff Type', type: 'select', options: [
        { value: 'linear', label: 'Linear' },
        { value: 'exponential', label: 'Exponential' },
        { value: 'gaussian', label: 'Gaussian' },
      ], defaultValue: 'linear' },
    ],
  },

  // ===== ANIMATIONS =====
  {
    type: 'click-spark',
    name: 'Click Spark',
    category: 'animations',
    icon: 'Zap',
    defaultProps: {
      sparkColor: '#fbbf24',
      sparkSize: 30,
      duration: 0.7,
    },
    configSchema: [
      { key: 'sparkColor', label: 'Spark Color', type: 'color', defaultValue: '#fbbf24' },
      { key: 'sparkSize', label: 'Spark Size', type: 'number', defaultValue: 30, min: 10, max: 100, step: 10 },
      { key: 'duration', label: 'Animation Duration', type: 'number', defaultValue: 0.7, min: 0.3, max: 2, step: 0.1 },
    ],
  },
  {
    type: 'bounce',
    name: 'Bounce Animation',
    category: 'animations',
    icon: 'ArrowBigUpDash',
    defaultProps: {
      bounceHeight: 20,
      duration: 1,
      repeat: true,
    },
    configSchema: [
      { key: 'bounceHeight', label: 'Bounce Height', type: 'number', defaultValue: 20, min: 5, max: 50, step: 5 },
      { key: 'duration', label: 'Animation Duration', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
      { key: 'repeat', label: 'Repeat Animation', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'magnet',
    name: 'Magnet Effect',
    category: 'animations',
    icon: 'Magnet',
    defaultProps: {
      strength: 30,
      radius: 100,
    },
    configSchema: [
      { key: 'strength', label: 'Magnet Strength', type: 'number', defaultValue: 30, min: 10, max: 100, step: 10 },
      { key: 'radius', label: 'Effect Radius', type: 'number', defaultValue: 100, min: 50, max: 300, step: 25 },
    ],
  },
  {
    type: 'star-border',
    name: 'Star Border',
    category: 'animations',
    icon: 'Star',
    defaultProps: {
      starColor: '#fbbf24',
      starSize: 20,
      speed: 2,
    },
    configSchema: [
      { key: 'starColor', label: 'Star Color', type: 'color', defaultValue: '#fbbf24' },
      { key: 'starSize', label: 'Star Size', type: 'number', defaultValue: 20, min: 10, max: 50, step: 5 },
      { key: 'speed', label: 'Animation Speed', type: 'number', defaultValue: 2, min: 0.5, max: 5, step: 0.5 },
    ],
  },
  {
    type: 'animated-content',
    name: 'Animated Content',
    category: 'animations',
    icon: 'Activity',
    defaultProps: {
      animation: 'fade',
      duration: 0.8,
      delay: 0,
    },
    configSchema: [
      { key: 'animation', label: 'Animation Type', type: 'select', options: [
        { value: 'fade', label: 'Fade' },
        { value: 'slide', label: 'Slide' },
        { value: 'scale', label: 'Scale' },
        { value: 'rotate', label: 'Rotate' },
      ], defaultValue: 'fade' },
      { key: 'duration', label: 'Duration (s)', type: 'number', defaultValue: 0.8, min: 0.1, max: 3, step: 0.1 },
      { key: 'delay', label: 'Delay (s)', type: 'number', defaultValue: 0, min: 0, max: 2, step: 0.1 },
    ],
  },
  {
    type: 'blob-cursor',
    name: 'Blob Cursor',
    category: 'animations',
    icon: 'Circle',
    defaultProps: {
      size: 40,
      color: 'rgba(99, 102, 241, 0.5)',
      smoothing: 0.2,
    },
    configSchema: [
      { key: 'size', label: 'Blob Size', type: 'number', defaultValue: 40, min: 20, max: 100, step: 10 },
      { key: 'color', label: 'Blob Color', type: 'color', defaultValue: 'rgba(99, 102, 241, 0.5)' },
      { key: 'smoothing', label: 'Smoothing', type: 'number', defaultValue: 0.2, min: 0.05, max: 0.5, step: 0.05 },
    ],
  },
  {
    type: 'crosshair',
    name: 'Crosshair',
    category: 'animations',
    icon: 'Crosshair',
    defaultProps: {
      size: 50,
      color: '#ffffff',
      thickness: 2,
    },
    configSchema: [
      { key: 'size', label: 'Crosshair Size', type: 'number', defaultValue: 50, min: 20, max: 100, step: 10 },
      { key: 'color', label: 'Crosshair Color', type: 'color', defaultValue: '#ffffff' },
      { key: 'thickness', label: 'Line Thickness', type: 'number', defaultValue: 2, min: 1, max: 5, step: 1 },
    ],
  },
  {
    type: 'cubes',
    name: 'Cubes',
    category: 'animations',
    icon: 'Box',
    defaultProps: {
      count: 10,
      size: 50,
      speed: 1,
    },
    configSchema: [
      { key: 'count', label: 'Cube Count', type: 'number', defaultValue: 10, min: 5, max: 30, step: 5 },
      { key: 'size', label: 'Cube Size', type: 'number', defaultValue: 50, min: 20, max: 100, step: 10 },
      { key: 'speed', label: 'Animation Speed', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
    ],
  },
  {
    type: 'fade-content',
    name: 'Fade Content',
    category: 'animations',
    icon: 'Eye',
    defaultProps: {
      blur: false,
      duration: 1000,
      delay: 0,
      easing: 'ease-out',
      threshold: 0.1,
      initialOpacity: 0,
    },
    configSchema: [
      { key: 'blur', label: 'Enable Blur', type: 'boolean', defaultValue: false },
      { key: 'duration', label: 'Duration (ms)', type: 'number', defaultValue: 1000, min: 100, max: 5000, step: 100 },
      { key: 'delay', label: 'Delay (ms)', type: 'number', defaultValue: 0, min: 0, max: 2000, step: 100 },
      { key: 'easing', label: 'Easing', type: 'select', options: [
        { value: 'ease-out', label: 'Ease Out' },
        { value: 'ease-in', label: 'Ease In' },
        { value: 'ease-in-out', label: 'Ease In Out' },
        { value: 'linear', label: 'Linear' },
      ], defaultValue: 'ease-out' },
      { key: 'threshold', label: 'Visibility Threshold', type: 'number', defaultValue: 0.1, min: 0, max: 1, step: 0.1 },
      { key: 'initialOpacity', label: 'Initial Opacity', type: 'number', defaultValue: 0, min: 0, max: 1, step: 0.1 },
    ],
  },
  {
    type: 'glare-hover',
    name: 'Glare Hover',
    category: 'animations',
    icon: 'Sparkle',
    defaultProps: {
      intensity: 0.5,
      color: 'rgba(255, 255, 255, 0.2)',
    },
    configSchema: [
      { key: 'intensity', label: 'Glare Intensity', type: 'number', defaultValue: 0.5, min: 0.1, max: 1, step: 0.1 },
      { key: 'color', label: 'Glare Color', type: 'color', defaultValue: 'rgba(255, 255, 255, 0.2)' },
    ],
  },
  {
    type: 'image-trail',
    name: 'Image Trail',
    category: 'animations',
    icon: 'Image',
    defaultProps: {
      images: [],
      trailCount: 5,
      fadeSpeed: 0.9,
    },
    configSchema: [
      { key: 'trailCount', label: 'Trail Count', type: 'number', defaultValue: 5, min: 3, max: 10, step: 1 },
      { key: 'fadeSpeed', label: 'Fade Speed', type: 'number', defaultValue: 0.9, min: 0.7, max: 0.95, step: 0.05 },
    ],
  },
  {
    type: 'magnet-lines',
    name: 'Magnet Lines',
    category: 'animations',
    icon: 'Zap',
    defaultProps: {
      lineCount: 20,
      lineColor: '#6366f1',
      maxDistance: 200,
    },
    configSchema: [
      { key: 'lineCount', label: 'Line Count', type: 'number', defaultValue: 20, min: 10, max: 50, step: 5 },
      { key: 'lineColor', label: 'Line Color', type: 'color', defaultValue: '#6366f1' },
      { key: 'maxDistance', label: 'Max Distance', type: 'number', defaultValue: 200, min: 100, max: 400, step: 50 },
    ],
  },
  {
    type: 'meta-balls',
    name: 'Meta Balls',
    category: 'animations',
    icon: 'CircleDot',
    defaultProps: {
      ballCount: 5,
      ballSize: 100,
      speed: 1,
    },
    configSchema: [
      { key: 'ballCount', label: 'Ball Count', type: 'number', defaultValue: 5, min: 3, max: 10, step: 1 },
      { key: 'ballSize', label: 'Ball Size', type: 'number', defaultValue: 100, min: 50, max: 200, step: 25 },
      { key: 'speed', label: 'Animation Speed', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
    ],
  },
  {
    type: 'metallic-paint',
    name: 'Metallic Paint',
    category: 'animations',
    icon: 'Paintbrush',
    defaultProps: {
      brushSize: 50,
      metallic: 0.8,
      roughness: 0.2,
    },
    configSchema: [
      { key: 'brushSize', label: 'Brush Size', type: 'number', defaultValue: 50, min: 20, max: 100, step: 10 },
      { key: 'metallic', label: 'Metallic', type: 'number', defaultValue: 0.8, min: 0, max: 1, step: 0.1 },
      { key: 'roughness', label: 'Roughness', type: 'number', defaultValue: 0.2, min: 0, max: 1, step: 0.1 },
    ],
  },
  {
    type: 'noise',
    name: 'Noise',
    category: 'animations',
    icon: 'Activity',
    defaultProps: {
      scale: 100,
      speed: 0.01,
      opacity: 0.3,
    },
    configSchema: [
      { key: 'scale', label: 'Noise Scale', type: 'number', defaultValue: 100, min: 50, max: 500, step: 50 },
      { key: 'speed', label: 'Animation Speed', type: 'number', defaultValue: 0.01, min: 0.001, max: 0.1, step: 0.001 },
      { key: 'opacity', label: 'Opacity', type: 'number', defaultValue: 0.3, min: 0.1, max: 1, step: 0.1 },
    ],
  },
  {
    type: 'pixel-trail',
    name: 'Pixel Trail',
    category: 'animations',
    icon: 'Grid3x3',
    defaultProps: {
      pixelSize: 10,
      trailLength: 20,
      color: '#6366f1',
    },
    configSchema: [
      { key: 'pixelSize', label: 'Pixel Size', type: 'number', defaultValue: 10, min: 5, max: 30, step: 5 },
      { key: 'trailLength', label: 'Trail Length', type: 'number', defaultValue: 20, min: 10, max: 50, step: 10 },
      { key: 'color', label: 'Trail Color', type: 'color', defaultValue: '#6366f1' },
    ],
  },
  {
    type: 'pixel-transition',
    name: 'Pixel Transition',
    category: 'animations',
    icon: 'Grid2x2',
    defaultProps: {
      pixelSize: 10,
      duration: 1,
      stagger: 0.005,
    },
    configSchema: [
      { key: 'pixelSize', label: 'Pixel Size', type: 'number', defaultValue: 10, min: 5, max: 30, step: 5 },
      { key: 'duration', label: 'Duration (s)', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
      { key: 'stagger', label: 'Stagger', type: 'number', defaultValue: 0.005, min: 0, max: 0.05, step: 0.005 },
    ],
  },
  {
    type: 'ribbons',
    name: 'Ribbons',
    category: 'animations',
    icon: 'Wind',
    defaultProps: {
      ribbonCount: 5,
      ribbonWidth: 20,
      speed: 1,
    },
    configSchema: [
      { key: 'ribbonCount', label: 'Ribbon Count', type: 'number', defaultValue: 5, min: 3, max: 10, step: 1 },
      { key: 'ribbonWidth', label: 'Ribbon Width', type: 'number', defaultValue: 20, min: 10, max: 50, step: 10 },
      { key: 'speed', label: 'Animation Speed', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
    ],
  },
  {
    type: 'shape-blur',
    name: 'Shape Blur',
    category: 'animations',
    icon: 'Shapes',
    defaultProps: {
      shape: 'circle',
      blurAmount: 20,
      size: 200,
    },
    configSchema: [
      { key: 'shape', label: 'Shape', type: 'select', options: [
        { value: 'circle', label: 'Circle' },
        { value: 'square', label: 'Square' },
        { value: 'triangle', label: 'Triangle' },
      ], defaultValue: 'circle' },
      { key: 'blurAmount', label: 'Blur Amount', type: 'number', defaultValue: 20, min: 0, max: 50, step: 5 },
      { key: 'size', label: 'Shape Size', type: 'number', defaultValue: 200, min: 100, max: 400, step: 50 },
    ],
  },
  {
    type: 'splash-cursor',
    name: 'Splash Cursor',
    category: 'animations',
    icon: 'Droplet',
    defaultProps: {
      splashColor: '#6366f1',
      splashSize: 100,
      duration: 0.6,
    },
    configSchema: [
      { key: 'splashColor', label: 'Splash Color', type: 'color', defaultValue: '#6366f1' },
      { key: 'splashSize', label: 'Splash Size', type: 'number', defaultValue: 100, min: 50, max: 200, step: 25 },
      { key: 'duration', label: 'Duration (s)', type: 'number', defaultValue: 0.6, min: 0.3, max: 1.5, step: 0.1 },
    ],
  },
  {
    type: 'target-cursor',
    name: 'Target Cursor',
    category: 'animations',
    icon: 'Target',
    defaultProps: {
      targetSize: 60,
      targetColor: '#ef4444',
      rotationSpeed: 1,
    },
    configSchema: [
      { key: 'targetSize', label: 'Target Size', type: 'number', defaultValue: 60, min: 30, max: 120, step: 15 },
      { key: 'targetColor', label: 'Target Color', type: 'color', defaultValue: '#ef4444' },
      { key: 'rotationSpeed', label: 'Rotation Speed', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
    ],
  },

  // ===== COMPONENTS =====
  {
    type: 'magic-bento',
    name: 'Magic Bento Grid',
    category: 'components',
    icon: 'LayoutGrid',
    defaultProps: {
      columns: 3,
      gap: 16,
      items: [],
    },
    configSchema: [
      { key: 'columns', label: 'Number of Columns', type: 'number', defaultValue: 3, min: 1, max: 6, step: 1 },
      { key: 'gap', label: 'Gap Size', type: 'number', defaultValue: 16, min: 0, max: 32, step: 4 },
    ],
  },
  {
    type: 'spotlight-card',
    name: 'Spotlight Card',
    category: 'components',
    icon: 'Square',
    defaultProps: {
      title: 'Spotlight Card',
      description: 'Hover to see the spotlight effect',
      backgroundColor: '#1a1a24',
      spotlightColor: '#6366f1',
    },
    configSchema: [
      { key: 'title', label: 'Card Title', type: 'string', defaultValue: 'Spotlight Card' },
      { key: 'description', label: 'Card Description', type: 'string', defaultValue: 'Hover to see the spotlight effect' },
      { key: 'backgroundColor', label: 'Background Color', type: 'color', defaultValue: '#1a1a24' },
      { key: 'spotlightColor', label: 'Spotlight Color', type: 'color', defaultValue: '#6366f1' },
    ],
  },
  {
    type: 'dock',
    name: 'Dock',
    category: 'components',
    icon: 'PanelBottom',
    defaultProps: {
      items: ['Home', 'About', 'Services', 'Contact'],
      magnification: 1.5,
    },
    configSchema: [
      { key: 'magnification', label: 'Magnification', type: 'number', defaultValue: 1.5, min: 1, max: 3, step: 0.1 },
    ],
  },
  {
    type: 'counter',
    name: 'Counter',
    category: 'components',
    icon: 'Calculator',
    defaultProps: {
      initialValue: 0,
      step: 1,
      min: -999,
      max: 999,
    },
    configSchema: [
      { key: 'initialValue', label: 'Initial Value', type: 'number', defaultValue: 0 },
      { key: 'step', label: 'Step Size', type: 'number', defaultValue: 1 },
      { key: 'min', label: 'Minimum Value', type: 'number', defaultValue: -999 },
      { key: 'max', label: 'Maximum Value', type: 'number', defaultValue: 999 },
    ],
  },
  {
    type: 'stepper',
    name: 'Stepper',
    category: 'components',
    icon: 'ListOrdered',
    defaultProps: {
      steps: ['Step 1', 'Step 2', 'Step 3'],
      currentStep: 0,
    },
    configSchema: [
      { key: 'currentStep', label: 'Current Step', type: 'number', defaultValue: 0, min: 0, max: 10 },
    ],
  },
  {
    type: 'animated-list',
    name: 'Animated List',
    category: 'components',
    icon: 'List',
    defaultProps: {
      items: ['Item 1', 'Item 2', 'Item 3'],
      stagger: 0.1,
      animation: 'fade',
    },
    configSchema: [
      { key: 'items', label: 'List Items (comma separated)', type: 'string', defaultValue: 'Item 1,Item 2,Item 3' },
      { key: 'stagger', label: 'Stagger Delay', type: 'number', defaultValue: 0.1, min: 0, max: 0.5, step: 0.05 },
      { key: 'animation', label: 'Animation Type', type: 'select', options: [
        { value: 'fade', label: 'Fade' },
        { value: 'slide', label: 'Slide' },
        { value: 'scale', label: 'Scale' },
      ], defaultValue: 'fade' },
    ],
  },
  {
    type: 'bounce-cards',
    name: 'Bounce Cards',
    category: 'components',
    icon: 'Layers',
    defaultProps: {
      cards: 3,
      bounceHeight: 20,
      stagger: 0.1,
    },
    configSchema: [
      { key: 'cards', label: 'Number of Cards', type: 'number', defaultValue: 3, min: 2, max: 6, step: 1 },
      { key: 'bounceHeight', label: 'Bounce Height', type: 'number', defaultValue: 20, min: 10, max: 50, step: 10 },
      { key: 'stagger', label: 'Stagger Delay', type: 'number', defaultValue: 0.1, min: 0, max: 0.5, step: 0.05 },
    ],
  },
  {
    type: 'card-swap',
    name: 'Card Swap',
    category: 'components',
    icon: 'RefreshCw',
    defaultProps: {
      frontContent: 'Front',
      backContent: 'Back',
      flipDuration: 0.6,
    },
    configSchema: [
      { key: 'frontContent', label: 'Front Content', type: 'string', defaultValue: 'Front' },
      { key: 'backContent', label: 'Back Content', type: 'string', defaultValue: 'Back' },
      { key: 'flipDuration', label: 'Flip Duration', type: 'number', defaultValue: 0.6, min: 0.3, max: 1.5, step: 0.1 },
    ],
  },
  {
    type: 'carousel',
    name: 'Carousel',
    category: 'components',
    icon: 'ChevronLeftRight',
    defaultProps: {
      items: ['Slide 1', 'Slide 2', 'Slide 3'],
      autoPlay: true,
      interval: 3000,
    },
    configSchema: [
      { key: 'items', label: 'Carousel Items (comma separated)', type: 'string', defaultValue: 'Slide 1,Slide 2,Slide 3' },
      { key: 'autoPlay', label: 'Auto Play', type: 'boolean', defaultValue: true },
      { key: 'interval', label: 'Interval (ms)', type: 'number', defaultValue: 3000, min: 1000, max: 10000, step: 500 },
    ],
  },
  {
    type: 'chroma-grid',
    name: 'Chroma Grid',
    category: 'components',
    icon: 'Grid3x3',
    defaultProps: {
      columns: 4,
      rows: 4,
      cellSize: 100,
    },
    configSchema: [
      { key: 'columns', label: 'Columns', type: 'number', defaultValue: 4, min: 2, max: 8, step: 1 },
      { key: 'rows', label: 'Rows', type: 'number', defaultValue: 4, min: 2, max: 8, step: 1 },
      { key: 'cellSize', label: 'Cell Size', type: 'number', defaultValue: 100, min: 50, max: 200, step: 25 },
    ],
  },
  {
    type: 'circular-gallery',
    name: 'Circular Gallery',
    category: 'components',
    icon: 'CircleDot',
    defaultProps: {
      images: [],
      radius: 200,
      itemSize: 80,
    },
    configSchema: [
      { key: 'radius', label: 'Gallery Radius', type: 'number', defaultValue: 200, min: 100, max: 400, step: 50 },
      { key: 'itemSize', label: 'Item Size', type: 'number', defaultValue: 80, min: 40, max: 150, step: 10 },
    ],
  },
  {
    type: 'decay-card',
    name: 'Decay Card',
    category: 'components',
    icon: 'Eraser',
    defaultProps: {
      decaySpeed: 0.01,
      threshold: 0.5,
    },
    configSchema: [
      { key: 'decaySpeed', label: 'Decay Speed', type: 'number', defaultValue: 0.01, min: 0.001, max: 0.1, step: 0.001 },
      { key: 'threshold', label: 'Decay Threshold', type: 'number', defaultValue: 0.5, min: 0.1, max: 0.9, step: 0.1 },
    ],
  },
  {
    type: 'elastic-slider',
    name: 'Elastic Slider',
    category: 'components',
    icon: 'Sliders',
    defaultProps: {
      min: 0,
      max: 100,
      value: 50,
      elasticity: 0.5,
    },
    configSchema: [
      { key: 'min', label: 'Min Value', type: 'number', defaultValue: 0 },
      { key: 'max', label: 'Max Value', type: 'number', defaultValue: 100 },
      { key: 'value', label: 'Initial Value', type: 'number', defaultValue: 50 },
      { key: 'elasticity', label: 'Elasticity', type: 'number', defaultValue: 0.5, min: 0.1, max: 1, step: 0.1 },
    ],
  },
  {
    type: 'flowing-menu',
    name: 'Flowing Menu',
    category: 'components',
    icon: 'Menu',
    defaultProps: {
      items: ['Home', 'About', 'Services', 'Contact'],
      flowSpeed: 1,
    },
    configSchema: [
      { key: 'items', label: 'Menu Items (comma separated)', type: 'string', defaultValue: 'Home,About,Services,Contact' },
      { key: 'flowSpeed', label: 'Flow Speed', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
    ],
  },
  {
    type: 'fluid-glass',
    name: 'Fluid Glass',
    category: 'components',
    icon: 'Droplet',
    defaultProps: {
      blur: 10,
      opacity: 0.3,
      borderRadius: 20,
    },
    configSchema: [
      { key: 'blur', label: 'Blur Amount', type: 'number', defaultValue: 10, min: 0, max: 30, step: 5 },
      { key: 'opacity', label: 'Opacity', type: 'number', defaultValue: 0.3, min: 0.1, max: 0.8, step: 0.1 },
      { key: 'borderRadius', label: 'Border Radius', type: 'number', defaultValue: 20, min: 0, max: 50, step: 10 },
    ],
  },
  {
    type: 'flying-posters',
    name: 'Flying Posters',
    category: 'components',
    icon: 'Image',
    defaultProps: {
      posters: [],
      flySpeed: 2,
      perspective: 1000,
    },
    configSchema: [
      { key: 'flySpeed', label: 'Fly Speed', type: 'number', defaultValue: 2, min: 0.5, max: 5, step: 0.5 },
      { key: 'perspective', label: 'Perspective', type: 'number', defaultValue: 1000, min: 500, max: 2000, step: 250 },
    ],
  },
  {
    type: 'folder',
    name: 'Folder',
    category: 'components',
    icon: 'Folder',
    defaultProps: {
      folderName: 'My Folder',
      isOpen: false,
      color: '#fbbf24',
    },
    configSchema: [
      { key: 'folderName', label: 'Folder Name', type: 'string', defaultValue: 'My Folder' },
      { key: 'isOpen', label: 'Initially Open', type: 'boolean', defaultValue: false },
      { key: 'color', label: 'Folder Color', type: 'color', defaultValue: '#fbbf24' },
    ],
  },
  {
    type: 'glass-icons',
    name: 'Glass Icons',
    category: 'components',
    icon: 'Sparkles',
    defaultProps: {
      icons: ['home', 'settings', 'user'],
      iconSize: 40,
      glassEffect: true,
    },
    configSchema: [
      { key: 'iconSize', label: 'Icon Size', type: 'number', defaultValue: 40, min: 20, max: 80, step: 10 },
      { key: 'glassEffect', label: 'Glass Effect', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'glass-surface',
    name: 'Glass Surface',
    category: 'components',
    icon: 'Square',
    defaultProps: {
      blur: 15,
      opacity: 0.2,
      reflection: true,
    },
    configSchema: [
      { key: 'blur', label: 'Blur Amount', type: 'number', defaultValue: 15, min: 0, max: 30, step: 5 },
      { key: 'opacity', label: 'Opacity', type: 'number', defaultValue: 0.2, min: 0.1, max: 0.5, step: 0.1 },
      { key: 'reflection', label: 'Show Reflection', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'gooey-nav',
    name: 'Gooey Nav',
    category: 'components',
    icon: 'Navigation',
    defaultProps: {
      items: ['Home', 'About', 'Contact'],
      gooeyness: 0.5,
    },
    configSchema: [
      { key: 'items', label: 'Nav Items (comma separated)', type: 'string', defaultValue: 'Home,About,Contact' },
      { key: 'gooeyness', label: 'Gooey Effect', type: 'number', defaultValue: 0.5, min: 0.1, max: 1, step: 0.1 },
    ],
  },
  {
    type: 'infinite-menu',
    name: 'Infinite Menu',
    category: 'components',
    icon: 'Infinity',
    defaultProps: {
      items: ['Item 1', 'Item 2', 'Item 3', 'Item 4'],
      scrollSpeed: 1,
    },
    configSchema: [
      { key: 'items', label: 'Menu Items (comma separated)', type: 'string', defaultValue: 'Item 1,Item 2,Item 3,Item 4' },
      { key: 'scrollSpeed', label: 'Scroll Speed', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
    ],
  },
  {
    type: 'infinite-scroll',
    name: 'Infinite Scroll',
    category: 'components',
    icon: 'ChevronsDown',
    defaultProps: {
      itemHeight: 100,
      gap: 20,
      speed: 1,
    },
    configSchema: [
      { key: 'itemHeight', label: 'Item Height', type: 'number', defaultValue: 100, min: 50, max: 300, step: 50 },
      { key: 'gap', label: 'Gap Between Items', type: 'number', defaultValue: 20, min: 0, max: 50, step: 10 },
      { key: 'speed', label: 'Scroll Speed', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
    ],
  },
  {
    type: 'lanyard',
    name: 'Lanyard',
    category: 'components',
    icon: 'Badge',
    defaultProps: {
      position: [0, 0, 30],
      gravity: [0, -40, 0],
      fov: 20,
      transparent: true,
    },
    configSchema: [
      { key: 'fov', label: 'Field of View', type: 'number', defaultValue: 20, min: 10, max: 50, step: 5 },
      { key: 'transparent', label: 'Transparent Background', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'masonry',
    name: 'Masonry',
    category: 'components',
    icon: 'LayoutGrid',
    defaultProps: {
      columns: 3,
      gap: 16,
      items: [],
    },
    configSchema: [
      { key: 'columns', label: 'Number of Columns', type: 'number', defaultValue: 3, min: 2, max: 6, step: 1 },
      { key: 'gap', label: 'Gap Size', type: 'number', defaultValue: 16, min: 8, max: 32, step: 8 },
    ],
  },
  {
    type: 'model-viewer',
    name: 'Model Viewer',
    category: 'components',
    icon: 'Box',
    defaultProps: {
      modelUrl: '',
      autoRotate: true,
      cameraControls: true,
    },
    configSchema: [
      { key: 'modelUrl', label: 'Model URL', type: 'string', defaultValue: '' },
      { key: 'autoRotate', label: 'Auto Rotate', type: 'boolean', defaultValue: true },
      { key: 'cameraControls', label: 'Camera Controls', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'pixel-card',
    name: 'Pixel Card',
    category: 'components',
    icon: 'Grid2x2',
    defaultProps: {
      pixelSize: 4,
      hoverEffect: true,
    },
    configSchema: [
      { key: 'pixelSize', label: 'Pixel Size', type: 'number', defaultValue: 4, min: 2, max: 10, step: 2 },
      { key: 'hoverEffect', label: 'Hover Effect', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'rolling-gallery',
    name: 'Rolling Gallery',
    category: 'components',
    icon: 'Images',
    defaultProps: {
      images: [],
      rollSpeed: 1,
      gap: 20,
    },
    configSchema: [
      { key: 'rollSpeed', label: 'Roll Speed', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
      { key: 'gap', label: 'Image Gap', type: 'number', defaultValue: 20, min: 10, max: 50, step: 10 },
    ],
  },
  {
    type: 'scroll-stack',
    name: 'Scroll Stack',
    category: 'components',
    icon: 'Layers',
    defaultProps: {
      cards: [],
      offset: 40,
      scaleFactor: 0.06,
    },
    configSchema: [
      { key: 'offset', label: 'Card Offset', type: 'number', defaultValue: 40, min: 20, max: 80, step: 10 },
      { key: 'scaleFactor', label: 'Scale Factor', type: 'number', defaultValue: 0.06, min: 0.02, max: 0.1, step: 0.02 },
    ],
  },
  {
    type: 'stack',
    name: 'Stack',
    category: 'components',
    icon: 'Layers',
    defaultProps: {
      items: [],
      spacing: 20,
      perspective: 1000,
    },
    configSchema: [
      { key: 'spacing', label: 'Item Spacing', type: 'number', defaultValue: 20, min: 10, max: 50, step: 10 },
      { key: 'perspective', label: 'Perspective', type: 'number', defaultValue: 1000, min: 500, max: 2000, step: 250 },
    ],
  },
  {
    type: 'tilted-card',
    name: 'Tilted Card',
    category: 'components',
    icon: 'Square',
    defaultProps: {
      tiltAmount: 15,
      perspective: 1000,
      scale: 1.05,
    },
    configSchema: [
      { key: 'tiltAmount', label: 'Tilt Amount', type: 'number', defaultValue: 15, min: 5, max: 30, step: 5 },
      { key: 'perspective', label: 'Perspective', type: 'number', defaultValue: 1000, min: 500, max: 2000, step: 250 },
      { key: 'scale', label: 'Hover Scale', type: 'number', defaultValue: 1.05, min: 1, max: 1.2, step: 0.05 },
    ],
  },

  // ===== BACKGROUNDS =====
  {
    type: 'aurora',
    name: 'Aurora Background',
    category: 'backgrounds',
    icon: 'Sparkles',
    defaultProps: {
      colors: ['#3b82f6', '#8b5cf6', '#ec4899'],
      speed: 3,
      opacity: 0.5,
    },
    configSchema: [
      { key: 'colors', label: 'Colors', type: 'color', defaultValue: ['#3b82f6', '#8b5cf6', '#ec4899'] },
      { key: 'speed', label: 'Animation Speed', type: 'number', defaultValue: 3, min: 1, max: 10, step: 1 },
      { key: 'opacity', label: 'Opacity', type: 'number', defaultValue: 0.5, min: 0, max: 1, step: 0.1 },
    ],
  },
  {
    type: 'waves',
    name: 'Waves Background',
    category: 'backgrounds',
    icon: 'Waves',
    defaultProps: {
      color: '#3b82f6',
      amplitude: 50,
      frequency: 0.01,
      speed: 0.8,
    },
    configSchema: [
      { key: 'color', label: 'Wave Color', type: 'color', defaultValue: '#3b82f6' },
      { key: 'amplitude', label: 'Wave Height', type: 'number', defaultValue: 50, min: 10, max: 100, step: 10 },
      { key: 'frequency', label: 'Wave Frequency', type: 'number', defaultValue: 0.01, min: 0.001, max: 0.05, step: 0.001 },
      { key: 'speed', label: 'Animation Speed', type: 'number', defaultValue: 0.8, min: 0.1, max: 2, step: 0.1 },
    ],
  },
  {
    type: 'grid',
    name: 'Grid Background',
    category: 'backgrounds',
    icon: 'Grid3x3',
    defaultProps: {
      color: '#2a2a3c',
      size: 50,
      opacity: 0.5,
    },
    configSchema: [
      { key: 'color', label: 'Grid Color', type: 'color', defaultValue: '#2a2a3c' },
      { key: 'size', label: 'Grid Size', type: 'number', defaultValue: 50, min: 20, max: 100, step: 10 },
      { key: 'opacity', label: 'Opacity', type: 'number', defaultValue: 0.5, min: 0, max: 1, step: 0.1 },
    ],
  },
  {
    type: 'particles',
    name: 'Particles',
    category: 'backgrounds',
    icon: 'Sparkle',
    defaultProps: {
      particleCount: 50,
      particleColor: '#ffffff',
      particleSize: 2,
      speed: 1,
    },
    configSchema: [
      { key: 'particleCount', label: 'Particle Count', type: 'number', defaultValue: 50, min: 10, max: 200, step: 10 },
      { key: 'particleColor', label: 'Particle Color', type: 'color', defaultValue: '#ffffff' },
      { key: 'particleSize', label: 'Particle Size', type: 'number', defaultValue: 2, min: 1, max: 10, step: 1 },
      { key: 'speed', label: 'Animation Speed', type: 'number', defaultValue: 1, min: 0.1, max: 5, step: 0.1 },
    ],
  },
  {
    type: 'dot-grid',
    name: 'Dot Grid',
    category: 'backgrounds',
    icon: 'CircleDot',
    defaultProps: {
      dotColor: '#6366f1',
      dotSize: 2,
      spacing: 30,
      opacity: 0.3,
    },
    configSchema: [
      { key: 'dotColor', label: 'Dot Color', type: 'color', defaultValue: '#6366f1' },
      { key: 'dotSize', label: 'Dot Size', type: 'number', defaultValue: 2, min: 1, max: 10, step: 1 },
      { key: 'spacing', label: 'Spacing', type: 'number', defaultValue: 30, min: 10, max: 100, step: 10 },
      { key: 'opacity', label: 'Opacity', type: 'number', defaultValue: 0.3, min: 0, max: 1, step: 0.1 },
    ],
  },
  {
    type: 'balatro',
    name: 'Balatro',
    category: 'backgrounds',
    icon: 'Sparkles',
    defaultProps: {
      pattern: 'dots',
      color1: '#1a1a2e',
      color2: '#16213e',
    },
    configSchema: [
      { key: 'pattern', label: 'Pattern Type', type: 'select', options: [
        { value: 'dots', label: 'Dots' },
        { value: 'lines', label: 'Lines' },
        { value: 'grid', label: 'Grid' },
      ], defaultValue: 'dots' },
      { key: 'color1', label: 'Primary Color', type: 'color', defaultValue: '#1a1a2e' },
      { key: 'color2', label: 'Secondary Color', type: 'color', defaultValue: '#16213e' },
    ],
  },
  {
    type: 'ballpit',
    name: 'Ballpit',
    category: 'backgrounds',
    icon: 'CircleDot',
    defaultProps: {
      count: 200,
      gravity: 0.5,
      friction: 0.9975,
      wallBounce: 0.95,
      followCursor: true,
      colors: [0, 0, 0],
      ambientColor: 16777215,
      ambientIntensity: 1,
      lightIntensity: 200,
      minSize: 0.5,
      maxSize: 1,
      size0: 1,
      maxVelocity: 0.15,
      maxX: 5,
      maxY: 5,
      maxZ: 2,
    },
    configSchema: [
      { key: 'count', label: 'Ball Count', type: 'number', defaultValue: 200, min: 50, max: 500, step: 50 },
      { key: 'gravity', label: 'Gravity', type: 'number', defaultValue: 0.5, min: 0, max: 2, step: 0.1 },
      { key: 'friction', label: 'Friction', type: 'number', defaultValue: 0.9975, min: 0.9, max: 1, step: 0.0025 },
      { key: 'followCursor', label: 'Follow Cursor', type: 'boolean', defaultValue: true },
      { key: 'minSize', label: 'Min Ball Size', type: 'number', defaultValue: 0.5, min: 0.1, max: 1, step: 0.1 },
      { key: 'maxSize', label: 'Max Ball Size', type: 'number', defaultValue: 1, min: 0.5, max: 2, step: 0.1 },
    ],
  },
  {
    type: 'beams',
    name: 'Beams',
    category: 'backgrounds',
    icon: 'Zap',
    defaultProps: {
      beamCount: 5,
      beamColor: '#6366f1',
      beamWidth: 2,
      speed: 1,
    },
    configSchema: [
      { key: 'beamCount', label: 'Beam Count', type: 'number', defaultValue: 5, min: 1, max: 10, step: 1 },
      { key: 'beamColor', label: 'Beam Color', type: 'color', defaultValue: '#6366f1' },
      { key: 'beamWidth', label: 'Beam Width', type: 'number', defaultValue: 2, min: 1, max: 10, step: 1 },
      { key: 'speed', label: 'Animation Speed', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
    ],
  },
  {
    type: 'dark-veil',
    name: 'Dark Veil',
    category: 'backgrounds',
    icon: 'Moon',
    defaultProps: {
      opacity: 0.8,
      gradientStart: '#000000',
      gradientEnd: '#1a1a1a',
    },
    configSchema: [
      { key: 'opacity', label: 'Veil Opacity', type: 'number', defaultValue: 0.8, min: 0.3, max: 1, step: 0.1 },
      { key: 'gradientStart', label: 'Gradient Start', type: 'color', defaultValue: '#000000' },
      { key: 'gradientEnd', label: 'Gradient End', type: 'color', defaultValue: '#1a1a1a' },
    ],
  },
  {
    type: 'dither',
    name: 'Dither',
    category: 'backgrounds',
    icon: 'Grid3x3',
    defaultProps: {
      ditherSize: 2,
      color1: '#ffffff',
      color2: '#000000',
    },
    configSchema: [
      { key: 'ditherSize', label: 'Dither Size', type: 'number', defaultValue: 2, min: 1, max: 8, step: 1 },
      { key: 'color1', label: 'Color 1', type: 'color', defaultValue: '#ffffff' },
      { key: 'color2', label: 'Color 2', type: 'color', defaultValue: '#000000' },
    ],
  },
  {
    type: 'grid-distortion',
    name: 'Grid Distortion',
    category: 'backgrounds',
    icon: 'Grid3x3',
    defaultProps: {
      gridSize: 50,
      distortionAmount: 0.5,
      animationSpeed: 1,
    },
    configSchema: [
      { key: 'gridSize', label: 'Grid Size', type: 'number', defaultValue: 50, min: 20, max: 100, step: 10 },
      { key: 'distortionAmount', label: 'Distortion', type: 'number', defaultValue: 0.5, min: 0, max: 1, step: 0.1 },
      { key: 'animationSpeed', label: 'Animation Speed', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
    ],
  },
  {
    type: 'grid-motion',
    name: 'Grid Motion',
    category: 'backgrounds',
    icon: 'Grid3x3',
    defaultProps: {
      cellSize: 40,
      speed: 1,
      perspective: 800,
    },
    configSchema: [
      { key: 'cellSize', label: 'Cell Size', type: 'number', defaultValue: 40, min: 20, max: 80, step: 10 },
      { key: 'speed', label: 'Motion Speed', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
      { key: 'perspective', label: 'Perspective', type: 'number', defaultValue: 800, min: 400, max: 1600, step: 200 },
    ],
  },
  {
    type: 'hyperspeed',
    name: 'Hyperspeed',
    category: 'backgrounds',
    icon: 'Zap',
    defaultProps: {
      speed: 1,
      starCount: 200,
      starColor: '#ffffff',
    },
    configSchema: [
      { key: 'speed', label: 'Warp Speed', type: 'number', defaultValue: 1, min: 0.5, max: 5, step: 0.5 },
      { key: 'starCount', label: 'Star Count', type: 'number', defaultValue: 200, min: 50, max: 500, step: 50 },
      { key: 'starColor', label: 'Star Color', type: 'color', defaultValue: '#ffffff' },
    ],
  },
  {
    type: 'iridescence',
    name: 'Iridescence',
    category: 'backgrounds',
    icon: 'Palette',
    defaultProps: {
      hueRotation: 0,
      saturation: 100,
      lightness: 50,
    },
    configSchema: [
      { key: 'hueRotation', label: 'Hue Rotation', type: 'number', defaultValue: 0, min: 0, max: 360, step: 30 },
      { key: 'saturation', label: 'Saturation %', type: 'number', defaultValue: 100, min: 0, max: 100, step: 10 },
      { key: 'lightness', label: 'Lightness %', type: 'number', defaultValue: 50, min: 0, max: 100, step: 10 },
    ],
  },
  {
    type: 'letter-glitch',
    name: 'Letter Glitch',
    category: 'backgrounds',
    icon: 'Type',
    defaultProps: {
      letters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
      glitchSpeed: 0.1,
      fontSize: 24,
    },
    configSchema: [
      { key: 'letters', label: 'Letters', type: 'string', defaultValue: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' },
      { key: 'glitchSpeed', label: 'Glitch Speed', type: 'number', defaultValue: 0.1, min: 0.01, max: 0.5, step: 0.01 },
      { key: 'fontSize', label: 'Font Size', type: 'number', defaultValue: 24, min: 12, max: 48, step: 6 },
    ],
  },
  {
    type: 'lightning',
    name: 'Lightning',
    category: 'backgrounds',
    icon: 'Zap',
    defaultProps: {
      frequency: 3,
      color: '#9333ea',
      branches: 5,
    },
    configSchema: [
      { key: 'frequency', label: 'Strike Frequency', type: 'number', defaultValue: 3, min: 1, max: 10, step: 1 },
      { key: 'color', label: 'Lightning Color', type: 'color', defaultValue: '#9333ea' },
      { key: 'branches', label: 'Branch Count', type: 'number', defaultValue: 5, min: 3, max: 10, step: 1 },
    ],
  },
  {
    type: 'liquid-chrome',
    name: 'Liquid Chrome',
    category: 'backgrounds',
    icon: 'Droplet',
    defaultProps: {
      viscosity: 0.5,
      metallic: 0.9,
      reflectivity: 0.8,
    },
    configSchema: [
      { key: 'viscosity', label: 'Viscosity', type: 'number', defaultValue: 0.5, min: 0.1, max: 1, step: 0.1 },
      { key: 'metallic', label: 'Metallic', type: 'number', defaultValue: 0.9, min: 0, max: 1, step: 0.1 },
      { key: 'reflectivity', label: 'Reflectivity', type: 'number', defaultValue: 0.8, min: 0, max: 1, step: 0.1 },
    ],
  },
  {
    type: 'orb',
    name: 'Orb',
    category: 'backgrounds',
    icon: 'Circle',
    defaultProps: {
      orbSize: 300,
      orbColor: '#6366f1',
      glowIntensity: 0.5,
    },
    configSchema: [
      { key: 'orbSize', label: 'Orb Size', type: 'number', defaultValue: 300, min: 100, max: 600, step: 50 },
      { key: 'orbColor', label: 'Orb Color', type: 'color', defaultValue: '#6366f1' },
      { key: 'glowIntensity', label: 'Glow Intensity', type: 'number', defaultValue: 0.5, min: 0.1, max: 1, step: 0.1 },
    ],
  },
  {
    type: 'ripple-grid',
    name: 'Ripple Grid',
    category: 'backgrounds',
    icon: 'Grid3x3',
    defaultProps: {
      gridSize: 40,
      rippleSpeed: 1,
      rippleSize: 100,
    },
    configSchema: [
      { key: 'gridSize', label: 'Grid Size', type: 'number', defaultValue: 40, min: 20, max: 80, step: 10 },
      { key: 'rippleSpeed', label: 'Ripple Speed', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
      { key: 'rippleSize', label: 'Ripple Size', type: 'number', defaultValue: 100, min: 50, max: 200, step: 25 },
    ],
  },
  {
    type: 'silk',
    name: 'Silk',
    category: 'backgrounds',
    icon: 'Wind',
    defaultProps: {
      waveCount: 5,
      waveSpeed: 0.5,
      color1: '#e879f9',
      color2: '#7c3aed',
    },
    configSchema: [
      { key: 'waveCount', label: 'Wave Count', type: 'number', defaultValue: 5, min: 3, max: 10, step: 1 },
      { key: 'waveSpeed', label: 'Wave Speed', type: 'number', defaultValue: 0.5, min: 0.1, max: 2, step: 0.1 },
      { key: 'color1', label: 'Color 1', type: 'color', defaultValue: '#e879f9' },
      { key: 'color2', label: 'Color 2', type: 'color', defaultValue: '#7c3aed' },
    ],
  },
  {
    type: 'squares',
    name: 'Squares',
    category: 'backgrounds',
    icon: 'Square',
    defaultProps: {
      squareSize: 50,
      gap: 10,
      color: '#2a2a2a',
    },
    configSchema: [
      { key: 'squareSize', label: 'Square Size', type: 'number', defaultValue: 50, min: 20, max: 100, step: 10 },
      { key: 'gap', label: 'Gap Size', type: 'number', defaultValue: 10, min: 0, max: 30, step: 5 },
      { key: 'color', label: 'Square Color', type: 'color', defaultValue: '#2a2a2a' },
    ],
  },
  {
    type: 'threads',
    name: 'Threads',
    category: 'backgrounds',
    icon: 'GitBranch',
    defaultProps: {
      threadCount: 10,
      threadColor: '#6366f1',
      animationSpeed: 1,
    },
    configSchema: [
      { key: 'threadCount', label: 'Thread Count', type: 'number', defaultValue: 10, min: 5, max: 20, step: 1 },
      { key: 'threadColor', label: 'Thread Color', type: 'color', defaultValue: '#6366f1' },
      { key: 'animationSpeed', label: 'Animation Speed', type: 'number', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
    ],
  },
];

export const getComponentDefinition = (type: string): ComponentDefinition | undefined => {
  return allComponentDefinitions.find((def) => def.type === type);
};

export const getDefaultSize = (type: string): ComponentSize => {
  return defaultSizes[type] || { width: '200px', height: '100px' };
};