// Re-export everything from the comprehensive definitions
export { allComponentDefinitions as componentDefinitions, getComponentDefinition, getDefaultSize, defaultSizes } from './all-definitions';

// Keep a subset of commonly used components for quick access
export const commonComponentDefinitions = [
  // Backgrounds
  {
    type: 'aurora',
    name: 'Aurora Background',
    category: 'backgrounds',
    icon: 'Sparkles',
    defaultProps: {
      colors: ['#3b82f6', '#8b5cf6', '#ec4899'],
      speed: 3,
      opacity: 0.5,
    },
    configSchema: [
      {
        key: 'colors',
        label: 'Colors',
        type: 'color',
        defaultValue: ['#3b82f6', '#8b5cf6', '#ec4899'],
      },
      {
        key: 'speed',
        label: 'Animation Speed',
        type: 'number',
        defaultValue: 3,
        min: 1,
        max: 10,
        step: 1,
      },
      {
        key: 'opacity',
        label: 'Opacity',
        type: 'number',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.1,
      },
    ],
  },
  {
    type: 'waves',
    name: 'Waves Background',
    category: 'backgrounds',
    icon: 'Waves',
    defaultProps: {
      color: '#3b82f6',
      amplitude: 50,
      frequency: 0.01,
      speed: 0.8,
    },
    configSchema: [
      {
        key: 'color',
        label: 'Wave Color',
        type: 'color',
        defaultValue: '#3b82f6',
      },
      {
        key: 'amplitude',
        label: 'Wave Height',
        type: 'number',
        defaultValue: 50,
        min: 10,
        max: 100,
        step: 10,
      },
      {
        key: 'frequency',
        label: 'Wave Frequency',
        type: 'number',
        defaultValue: 0.01,
        min: 0.001,
        max: 0.05,
        step: 0.001,
      },
      {
        key: 'speed',
        label: 'Animation Speed',
        type: 'number',
        defaultValue: 0.8,
        min: 0.1,
        max: 2,
        step: 0.1,
      },
    ],
  },
  {
    type: 'grid',
    name: 'Grid Background',
    category: 'backgrounds',
    icon: 'Grid3x3',
    defaultProps: {
      color: '#e5e7eb',
      size: 50,
      opacity: 0.5,
    },
    configSchema: [
      {
        key: 'color',
        label: 'Grid Color',
        type: 'color',
        defaultValue: '#e5e7eb',
      },
      {
        key: 'size',
        label: 'Grid Size',
        type: 'number',
        defaultValue: 50,
        min: 20,
        max: 100,
        step: 10,
      },
      {
        key: 'opacity',
        label: 'Opacity',
        type: 'number',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.1,
      },
    ],
  },
  
  // Text Animations
  {
    type: 'rolling-text',
    name: 'Rolling Text',
    category: 'text',
    icon: 'Type',
    defaultProps: {
      text: 'Rolling Text Animation',
      fontSize: '48px',
      color: '#000000',
      duration: 2,
    },
    configSchema: [
      {
        key: 'text',
        label: 'Text Content',
        type: 'string',
        defaultValue: 'Rolling Text Animation',
      },
      {
        key: 'fontSize',
        label: 'Font Size',
        type: 'string',
        defaultValue: '48px',
      },
      {
        key: 'color',
        label: 'Text Color',
        type: 'color',
        defaultValue: '#000000',
      },
      {
        key: 'duration',
        label: 'Animation Duration',
        type: 'number',
        defaultValue: 2,
        min: 0.5,
        max: 5,
        step: 0.5,
      },
    ],
  },
  {
    type: 'split-text',
    name: 'Split Text',
    category: 'text',
    icon: 'SplitSquareHorizontal',
    defaultProps: {
      text: 'Split Text Effect',
      fontSize: '36px',
      color: '#000000',
      splitBy: 'words',
      stagger: 0.1,
    },
    configSchema: [
      {
        key: 'text',
        label: 'Text Content',
        type: 'string',
        defaultValue: 'Split Text Effect',
      },
      {
        key: 'fontSize',
        label: 'Font Size',
        type: 'string',
        defaultValue: '36px',
      },
      {
        key: 'color',
        label: 'Text Color',
        type: 'color',
        defaultValue: '#000000',
      },
      {
        key: 'splitBy',
        label: 'Split By',
        type: 'select',
        options: [
          { value: 'chars', label: 'Characters' },
          { value: 'words', label: 'Words' },
        ],
        defaultValue: 'words',
      },
      {
        key: 'stagger',
        label: 'Stagger Delay',
        type: 'number',
        defaultValue: 0.1,
        min: 0,
        max: 0.5,
        step: 0.05,
      },
    ],
  },
  
  // Components
  {
    type: 'magic-bento',
    name: 'Magic Bento Grid',
    category: 'components',
    icon: 'LayoutGrid',
    defaultProps: {
      columns: 3,
      gap: 16,
      items: [],
    },
    configSchema: [
      {
        key: 'columns',
        label: 'Number of Columns',
        type: 'number',
        defaultValue: 3,
        min: 1,
        max: 6,
        step: 1,
      },
      {
        key: 'gap',
        label: 'Gap Size',
        type: 'number',
        defaultValue: 16,
        min: 0,
        max: 32,
        step: 4,
      },
    ],
  },
  {
    type: 'spotlight-card',
    name: 'Spotlight Card',
    category: 'components',
    icon: 'Square',
    defaultProps: {
      title: 'Spotlight Card',
      description: 'Hover to see the spotlight effect',
      backgroundColor: '#ffffff',
      spotlightColor: '#3b82f6',
    },
    configSchema: [
      {
        key: 'title',
        label: 'Card Title',
        type: 'string',
        defaultValue: 'Spotlight Card',
      },
      {
        key: 'description',
        label: 'Card Description',
        type: 'string',
        defaultValue: 'Hover to see the spotlight effect',
      },
      {
        key: 'backgroundColor',
        label: 'Background Color',
        type: 'color',
        defaultValue: '#ffffff',
      },
      {
        key: 'spotlightColor',
        label: 'Spotlight Color',
        type: 'color',
        defaultValue: '#3b82f6',
      },
    ],
  },
  
  // Animations
  {
    type: 'click-spark',
    name: 'Click Spark',
    category: 'animations',
    icon: 'Zap',
    defaultProps: {
      sparkColor: '#fbbf24',
      sparkSize: 30,
      duration: 0.7,
    },
    configSchema: [
      {
        key: 'sparkColor',
        label: 'Spark Color',
        type: 'color',
        defaultValue: '#fbbf24',
      },
      {
        key: 'sparkSize',
        label: 'Spark Size',
        type: 'number',
        defaultValue: 30,
        min: 10,
        max: 100,
        step: 10,
      },
      {
        key: 'duration',
        label: 'Animation Duration',
        type: 'number',
        defaultValue: 0.7,
        min: 0.3,
        max: 2,
        step: 0.1,
      },
    ],
  },
  {
    type: 'bounce',
    name: 'Bounce Animation',
    category: 'animations',
    icon: 'ArrowBigUpDash',
    defaultProps: {
      bounceHeight: 20,
      duration: 1,
      repeat: true,
    },
    configSchema: [
      {
        key: 'bounceHeight',
        label: 'Bounce Height',
        type: 'number',
        defaultValue: 20,
        min: 5,
        max: 50,
        step: 5,
      },
      {
        key: 'duration',
        label: 'Animation Duration',
        type: 'number',
        defaultValue: 1,
        min: 0.5,
        max: 3,
        step: 0.5,
      },
      {
        key: 'repeat',
        label: 'Repeat Animation',
        type: 'boolean',
        defaultValue: true,
      },
    ],
  },
];